// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPfAklOgWCcEQtVCT8jRBpmYmdbQQoNc0',
    appId: '1:543739011560:web:ffba54a496948ab363845d',
    messagingSenderId: '543739011560',
    projectId: 'farwell-interview',
    authDomain: 'farwell-interview.firebaseapp.com',
    storageBucket: 'farwell-interview.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8wM6F8aD2z86JvrWfB09VIhf8oiTbXzw',
    appId: '1:543739011560:android:9ad84b2b220b773363845d',
    messagingSenderId: '543739011560',
    projectId: 'farwell-interview',
    storageBucket: 'farwell-interview.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIpa0230P_rPkGWwzsDQkua6HPfyqfZMU',
    appId: '1:543739011560:ios:2ac353aecf895f1363845d',
    messagingSenderId: '543739011560',
    projectId: 'farwell-interview',
    storageBucket: 'farwell-interview.appspot.com',
    iosClientId: '543739011560-lkc9cpv93a4cpvg4cqbdvj3m0r6tlumj.apps.googleusercontent.com',
    iosBundleId: 'com.example.authTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIpa0230P_rPkGWwzsDQkua6HPfyqfZMU',
    appId: '1:543739011560:ios:2ac353aecf895f1363845d',
    messagingSenderId: '543739011560',
    projectId: 'farwell-interview',
    storageBucket: 'farwell-interview.appspot.com',
    iosClientId: '543739011560-lkc9cpv93a4cpvg4cqbdvj3m0r6tlumj.apps.googleusercontent.com',
    iosBundleId: 'com.example.authTest',
  );
}
